name: Robot Framework Tests

on:
  pull_request:
    branches:
      - main

jobs:
  robot-framework-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests
          pip install robotframework-faker
          pip install webdriver-manager

      - name: Setup Chrome and ChromeDriver
        run: |
          google-chrome --version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          wget -q https://storage.googleapis.com/chrome-for-testing-public/$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r '.channels.Stable.version')/linux64/chromedriver-linux64.zip 
          unzip -q chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Run Login Test Only
        env:
          CI: true
        run: |
          robot --outputdir results --test "Cenario 00: Login com sucesso" robot-framework-frontend/blacklist_T15_editar_departamento/tests/cliente/departamento.robot
        continue-on-error: false

      - name: Check Test Results
        run: |
          cd results
          if grep -q "FAIL" output.xml; then
            echo "❌️ Testes falharam!"
            exit 1
          else
            echo "✅ Todos os testes passaram!"
          fi
